// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// DeployVerificationBadge renders a compact inline badge that lazy-loads
// deploy verification status from the engine. On "missing", it updates the
// adjacent status badge to "draft" and removes itself (no page reload).
func DeployVerificationBadge(workflowID string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<span class=\"deploy-verification-badge\" hx-get=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs("/api/workflows/" + workflowID + "/deploy/status")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/templates/partials/deploy_status.templ`, Line: 9, Col: 60}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-trigger=\"load delay:200ms\" hx-swap=\"none\" x-data=\"{ verification: '' }\" @htmx:after-request.camel=\"\n\t\t\ttry {\n\t\t\t\tlet data = JSON.parse($event.detail.xhr.responseText);\n\t\t\t\t$data.verification = data.verification;\n\t\t\t\tif (data.verification === 'missing') {\n\t\t\t\t\t$el.closest('.workflow-card-header').querySelector('.badge').textContent = 'draft';\n\t\t\t\t\t$el.closest('.workflow-card-header').querySelector('.badge').className = 'badge badge-draft';\n\t\t\t\t\t$el.remove();\n\t\t\t\t}\n\t\t\t} catch(e) {}\n\t\t\"><template x-if=\"verification === 'verified'\"><span class=\"badge badge-success\" title=\"Engine confirms deployment\">&#x2713;</span></template><template x-if=\"verification === 'error'\"><span class=\"badge badge-warning\" title=\"Could not reach engine\">&#x26A0;</span></template></span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
